---
# tasks/main.yml
- name: Install HAProxy
  apt:
    name: haproxy
    state: present
    update_cache: yes

- name: Copy HAProxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
  notify:
    - Restart HAProxy

- name: Ensure HAProxy is started and enabled at boot
  systemd:
    name: haproxy
    state: started
    enabled: yes

- name: Configure firewall to allow HTTP traffic
  shell: 
    cmd: firewall-cmd --permanent --add-port=80/tcp
  args:
    warn: false

- name: Reload firewall
  shell:
    cmd: firewall-cmd --reload
  args:
    warn: false